// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgzEqA3wof-ZUlW4PTXgezTun7zmWQjFw',
    appId: '1:889789486345:web:4d741fb018694b4cec6fd8',
    messagingSenderId: '889789486345',
    projectId: 'clranhs-ict',
    authDomain: 'clranhs-ict.firebaseapp.com',
    storageBucket: 'clranhs-ict.appspot.com',
    measurementId: 'G-ERJZNVZ79B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-0Ar2dmSzkOv4d0Un5TVWqRLXf2-S1UY',
    appId: '1:889789486345:android:c6316425f891fc32ec6fd8',
    messagingSenderId: '889789486345',
    projectId: 'clranhs-ict',
    storageBucket: 'clranhs-ict.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9ocLCup27GzbEjhe2wz4UzDS64aGn0Mk',
    appId: '1:889789486345:ios:d22c0f54c1ef124eec6fd8',
    messagingSenderId: '889789486345',
    projectId: 'clranhs-ict',
    storageBucket: 'clranhs-ict.appspot.com',
    iosBundleId: 'com.example.clranhsIctApp',
  );
}
